language: node_js
node_js:
- '9'
sudo: required
addons:
  chrome: stable
before_install:
- npm install -g typescript && tsc -v
- npm install -g karma
install:
- npm install
script:
- npm run test
- npm run build
