language: node_js
node_js:
- '0.12'
sudo: required
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
- nvm install 12
- npm install -g npm && node -v && npm -v
- npm install -g typescript && tsc -v
- npm install -g karma
install:
- npm install
script:
- npm run test
- npm run build
